name: CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ make dpkg-dev libfuse3-dev fuse3 pkg-config

      - name: Build project
        run: |
          cd kubsh-shell
          make build

      - name: Pull test image
        run: docker pull tyvik/kubsh_test:master

      - name: Run tests
        run: |
          cd kubsh-shell
          make test

      - name: Build deb package
        run: |
          cd kubsh-shell
          make package

      - name: Upload deb package
        uses: actions/upload-artifact@v4
        with:
          name: kubsh-deb-package
          path: kubsh-shell/kubsh_*.deb
